### ISSUE TITLE
Generates code from imported types

### ISSUE THREAD

**Issue by smyrman** [semrush/zenrpc#52]
When running zenrpc in a package that both defines and imports a `Service` pacakge, then it will generate (incorrect) code for the imported serivies.

I.e. if having:
```
cmd/mycmd
    main_zenrpc.go -- generated
    service.go -- defines FooService
    server.go -- register FooService and pkg/bar.Service
pkg/bar
   bar_zenrpc.go -- generated
   service.go -- defines Service
```

When generating the code in `cmd/mycmd` then it will generate code for `Service` (which does not exist in the package) as well as FooService, which does exist. It will also, for some reason, import `encoding/json` twise. Either way, the result is invalid code.

Maybe related with #35?

**Comment by dizzyfool** [comment]
Should be working now, please confirm

**Comment by smyrman** [comment]
Sorry for the late update. It seams that we no longer get the additional `Service` generation. However, we still get a duplicated import:

Import:

```go
import (
	"context"
	"encoding/json"

	"github.com/semrush/zenrpc/v2"
	"github.com/semrush/zenrpc/v2/smd"

	"encoding/json"
)
```
